# This is a file written in Emacs and authored using org-mode (http://orgmode.org/)
# The "README.md" file is generated from this file by running the
# "M-x org-md-export-to-markdown" command from inside of Emacs.
#
# Don't render a Table of Contents 
#+OPTIONS: toc:nil
# Don't render section numbers
#+OPTIONS: num:nil
# Turn of subscript parsing: http://super-user.org/wordpress/2012/02/02/how-to-get-rid-of-subscript-annoyance-in-org-mode/comment-page-1/
#+OPTIONS: ^:{}
* Introduction
  This is an example PHP application that makes use of the
  [[https://simplesamlphp.org/][SimpleSAMLphp]] library support Single Sign-On with SAML.
* Requirements
  This example application depends on SimpleSAMLphp being installed in
  "../simplesamlphp". Meaning, this example expects SimpleSAMLphp to
  be installed one level up from this example in a folder called
  "simplesamlphp".
* Setting up Okta

  Before you can configure your application SimpleSAMLphp you 
  will need to set up an Okta "[[https://support.okta.com/articles/Knowledge_Article/27838096-Okta-Terminology][chiclet]]" (application icon) that enables an Okta 
  user to sign in to your to your application with SAML and SimpleSAMLphp.

  To set up Okta to connect to your application, follow the
  [[http://developer.okta.com/docs/guides/setting_up_a_saml_application_in_okta.html][setting up a SAML application in Okta]] guide. 
  As noted in the instructions, there are two steps to change:

  *In step #6*: 

  Use "SimpleSAMLphp Example" instead of "Example SAML application".

  *In step #7*: 

  When entering the URL
  #+BEGIN_HTML
  ```
  http://example.com/saml/sso/example-okta-com
  ```
  #+END_HTML

  instead, use the following:

  For "Single sign on URL" use:
  #+BEGIN_HTML
  ```
  http://PATH_TO_INSTALL_DIRECTORY/simplesamlphp/www/module.php/saml/sp/saml2-acs.php/example
  ```
  #+END_HTML

  For "Audience URI (SP Entity ID)" use:
  #+BEGIN_HTML
  ```
  http://PATH_TO_INSTALL_DIRECTORY/simplesamlphp/www/module.php/saml/sp/metadata.php/example
  ```
  #+END_HTML

  For "Default RelayState" use:
  #+BEGIN_HTML
  ```
  http://PATH_TO_INSTALL_DIRECTORY/okta-simplesamlphp-example/?saml_sso=example
  ```
  #+END_HTML

  *Note:*
  "PATH_TO_INSTALL_DIRECTORY" is the full path to the directory where SimpleSAMLphp and this application reside.
  It might look like: "example.com" or might contain a path like "example.com/path". 
  This will depend on how your webserver is set up.

* Setting up SimpleSAMLphp
  1. Use `git clone` to pull down this git repository.
  2. Copy the `saml-autoconfig.php` file to the directory for SimpleSAMLphp.
     Assuming that you cloned this repository to the same level as
     SimpleSAMLphp, this is the command you will use to do this:
     #+BEGIN_HTML
     ```shell 
     $ cp okta-simplesamlphp-example/saml-autoconfig.php simplesamlphp/ 
     ```
     #+END_HTML
  3. In the 'simplesamlphp' directory, 
     edit the `config/authsources.php` 
     and `metadata/saml20-idp-remote.php` files and add the line below to each file:
     #+BEGIN_HTML
     ```php
     require(dirname(__FILE__).'/../saml-autoconfig.php');
     ```
     #+END_HTML
  4. Finally, open the `saml-autoconfig.php` file in your favorite text editor.
     In the `$metadata_url_for` array, add an entry where the key is a
     string like "example" and the value is the metadata URL you got
     from the "Setting up Okta" section above. It should look like this:
     #+BEGIN_HTML
     ```php
     $metadata_url_for = array(
         'example' => 'https://example.okta.com/app/abc0de1fghIjKlMNo2p3/sso/saml/metadata',
     );
     ```
     #+END_HTML
* Testing
  1. Load the URL for `okta-simplesamlphp-example/index.php` in your web browser. 
     Try to log in to the 'example' IdP.
  2. In Okta, try clicking on the "SimpleSAMLphp Example" chiclet.
* Contact
  Updates or corrections to this document are very welcome. Feel free
  to send me [[https://help.github.com/articles/using-pull-requests/][pull requests]] with suggestions.

  # In a (perhaps fruitless) effort to avoid getting more spam, I've
  # encoded my email address using HTML entities.
  Additionally, please send me comments or questions via email: &#106;&#111;&#101;&#108;&#046;&#102;&#114;&#097;&#110;&#117;&#115;&#105;&#099;&#064;&#111;&#107;&#116;&#097;&#046;&#099;&#111;&#109;

